<a href="https://colab.research.google.com/github/kjapan87/TextGenerationV1/blob/main/TextGenerationExample1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def readFile(filePath):
    with open(filePath) as f:
        text = f.read()
    return text

import spacy
obj1 = spacy.load("en_core_web_sm")


In [ ]:
def PreProcess(doctext):
    return [token.text.lower() for token in obj1(doctext)]

In [ ]:
d=readFile("moby_dick_four_chapters.txt")
token =PreProcess(d)

In [ ]:
token

['call',
 'me',
 'ishmael',
 '.',
 ' ',
 'some',
 'years',
 'ago',
 '--',
 'never',
 'mind',
 'how',
 'long',
 '\n',
 'precisely',
 '--',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 ',',
 'and',
 'nothing',
 '\n',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 ',',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 '\n',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 '.',
 ' ',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 '\n',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 '.',
 ' ',
 'whenever',
 'i',
 '\n',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 ';',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 ',',
 '\n',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 ';',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 '\n',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 ',',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',


In [ ]:
type(token)

list

In [ ]:
len(token)

14481

In [ ]:
for i in range(0,14481):
  seq=[0,26]
  sequencelength= ''.join(seq)

TypeError: ignored

In [ ]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(token)):
    
    # Grab train_len# amount of characters
    seq = token[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [ ]:
seq

['marched',
 'out',
 '\n',
 'of',
 'the',
 'room',
 ',',
 'wrapped',
 'up',
 'in',
 'his',
 'great',
 'pilot',
 'monkey',
 'jacket',
 ',',
 'and',
 '\n',
 'sporting',
 'his',
 'harpoon',
 'like',
 'a',
 'marshal',
 "'s",
 'baton']

In [ ]:
from keras.preprocessing.text import text_to_word_sequence
obj2 = text_to_word_sequence(d)

In [ ]:
print(obj2)

['call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to', 'interest', 'me', 'on', 'shore', 'i', 'thought', 'i', 'would', 'sail', 'about', 'a', 'little', 'and', 'see', 'the', 'watery', 'part', 'of', 'the', 'world', 'it', 'is', 'a', 'way', 'i', 'have', 'of', 'driving', 'off', 'the', 'spleen', 'and', 'regulating', 'the', 'circulation', 'whenever', 'i', 'find', 'myself', 'growing', 'grim', 'about', 'the', 'mouth', 'whenever', 'it', 'is', 'a', 'damp', 'drizzly', 'november', 'in', 'my', 'soul', 'whenever', 'i', 'find', 'myself', 'involuntarily', 'pausing', 'before', 'coffin', 'warehouses', 'and', 'bringing', 'up', 'the', 'rear', 'of', 'every', 'funeral', 'i', 'meet', 'and', 'especially', 'whenever', 'my', 'hypos', 'get', 'such', 'an', 'upper', 'hand', 'of', 'me', 'that', 'it', 'requires', 'a', 'strong', 'moral', 'principle', 'to', 'prevent', 'me', 'from', '

In [ ]:
len(obj2)

11253

In [ ]:
type(obj2)

list

In [ ]:
import numpy as np
obj2 = np.array(obj2)

In [ ]:
print(obj2)
obj2.size

['call' 'me' 'ishmael' ... 'a' "marshal's" 'baton']


11253

In [ ]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.text import text_to_word_sequence

# estimate the size of the vocabulary
vocab_size = len(obj2)
print(vocab_size)
# integer encode the document
result = one_hot(d, vocab_size)
print(result)

11253
[411, 1001, 5030, 6446, 3085, 6249, 2367, 8132, 2463, 2406, 1147, 7085, 10439, 9469, 4152, 9678, 7413, 162, 8136, 3551, 735, 400, 9609, 5763, 1001, 431, 928, 3105, 7920, 3105, 7196, 3917, 64, 2981, 10439, 3551, 2561, 9560, 1935, 5571, 6551, 9560, 2174, 8169, 5909, 2981, 7568, 3105, 7738, 6551, 8550, 8936, 9560, 3827, 3551, 1768, 9560, 5781, 1887, 3105, 11012, 10408, 2798, 1410, 64, 9560, 3363, 1887, 8169, 5909, 2981, 654, 4605, 8668, 7413, 162, 10579, 1887, 3105, 11012, 10408, 1561, 6454, 2072, 994, 9427, 3551, 2304, 10860, 9560, 6572, 6551, 9313, 1589, 3105, 8863, 3551, 3369, 1887, 162, 221, 7883, 6888, 7656, 3088, 4474, 6551, 1001, 3381, 8169, 9181, 2981, 4277, 6386, 3488, 9609, 9949, 1001, 6532, 727, 7442, 869, 9560, 10485, 3551, 1249, 10974, 3571, 6673, 8936, 10581, 3105, 10822, 8169, 138, 1564, 9609, 7883, 9609, 9625, 2492, 6751, 2492, 3105, 7015, 11233, 5909, 162, 7759, 10115, 5188, 3551, 318, 3570, 2981, 6326, 6836, 113, 8030, 664, 3669, 7308, 535, 3105, 641, 10000, 9609, 

In [ ]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical #each of word  usage would  create a column

# one hot encode
encoded = to_categorical(result)
print(encoded)
# invert encoding
##inverted = argmax(encoded[0])
#print(inverted)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [ ]:
def createModel(vocab_size,obj2):
  model = Sequential()
  model.add(Embedding(11253,64,input_length=obj2)) #embedding layer task is converting vocabulary to a specific size
  model.add(LSTM(64,return_sequences=True)) #input layer
  model.add(LSTM(64,activation="tanh")) #hidden layer
  model.add(Dense(64,activation="relu"))#hidden layer
  model.add(Dense(vocab_size,activation="softmax"))#output layer
  model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"]) #compile layer together
  model.summary()
  return model

In [ ]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [ ]:
X = encoded[:,:-1]

In [ ]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
y= encoded[:,-1]

In [ ]:
y

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
seq_len = X.shape[1]

In [ ]:
model = createModel(vocab_size, seq_len)

In [ ]:
from pickle import dump,load

In [ ]:
X.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
X.shape

(11253, 11248)

In [ ]:
y.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
model.fit(X, y, batch_size=128, epochs=300,verbose=1)

Epoch 1/300


ValueError: ignored

In [ ]:
#1. Create & Read File
#2. Pre-processing
#3. From pre-processing we get tokenized words array
#4. word Array to integer array
#5. 